/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AckPacket, AckPacket, AUTO)


PB_BIND(SensorPacket, SensorPacket, AUTO)


PB_BIND(MausOutgoingMessage, MausOutgoingMessage, AUTO)


PB_BIND(MsgInit, MsgInit, AUTO)


PB_BIND(MsgControl, MsgControl, AUTO)


PB_BIND(MausIncomingMessage, MausIncomingMessage, AUTO)




